### ISSUE TITLE
Page template should be done within the Reactjs app

### ISSUE THREAD

**Issue by ACPK** [adnils/pwrs#2]
<div class="container">
        <div class="header">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
          <span class="logo"></span>
        </div>

        <p class="alert alert-info"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger"><%= get_flash(@conn, :error) %></p>

        <%= @inner %>

      </div>

**Comment by adnils** [comment]
Leaving it as it is for now as to not complicate routing for pages you want to render with Phoenix, I may look into this at a later date if it becomes an issue.
