### ISSUE TITLE
Use Flux

### ISSUE THREAD

**Issue by ACPK** [adnils/pwrs#3]
See: https://www.codementor.io/reactjs/tutorial/react-js-flux-architecture-tutorial

**Comment by adnils** [comment]
Even though I like the flux architecture, I think implementing it into this simple boilerplate is a bit out of scope. I would like to keep this project as un-opinionated, flexible and easy to maintain as possible.

There is however a definite possibility that I will release a more complete and opinionated stack in the near future, depending on the needs of my projects. [Redux](https://github.com/gaearon/redux), Relay and GraphQL are some very interesting ideas that I would consider for such a project.
